name: aarch64 CI

on: [push]

jobs:
  actions_job:
    runs-on: ubuntu-latest
    name: A job to test the multi architecture action
    steps:
    - uses: actions/checkout@v1
    - name: Run some commands on arm64 system
      id: runcmd
      uses: WongTusnYan/bolt@master
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
         apt-get update
         uname -a
         whoami
         cat /etc/issue
         lscpu
         df -h
         pwd
         ls /github/workspace
         apt install -y build-essential
         apt-get install -y manpages-dev
         gcc --version
         apt-get install -y autoconf automake libtool curl make g++ unzip git
         apt-get install -y libprotobuf-dev protobuf-compiler
         protoc --version
