name: aarch64 CI

on: [push]

jobs:
  actions_job:
    runs-on: ubuntu-latest
    name: A job to test the multi architecture action
    steps:
    - uses: actions/checkout@v1
    - name: Run some commands on arm64 system
      id: runcmd
      uses: WongTusnYan/bolt@master
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
         apt-get update
         uname -a
         whoami
         cat /etc/issue
         lscpu
         df -h
         pwd
         ls /github/workspace
         apt install -y build-essential
         apt-get install -y manpages-dev
         gcc --version
         apt-get install -y wget
         apt-get install -y cmake
         cmake --version
         make --version
         apt-get install -y libpng-dev
         apt-get install -y libjpeg-dev
         DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration -y
         apt-get install -y xorg
         apt-get install -y openbox
         apt-get install -y xauth
         apt-get install -y libx11-xcb-dev
         apt-get install -y zlib1g-dev
         apt-get install -y autoconf automake libtool curl make g++ unzip git
         apt-get install -y libprotobuf-dev protobuf-compiler
         protoc --version
         cd /github/workspace
         git clone https://github.com/dtschump/CImg.git
         cd CImg/
         mkdir include
         cp CImg.h include/
         ls include/
         export CImg_ROOT=/github/workspace/CImg
         export BOLT_ROOT=/github/workspace/
         cd /github/workspace
         mkdir build
         cd build
         cmake .. -DCMAKE_INSTALL_PREFIX=${BOLT_ROOT}
         make -j2
         make install -j2
