name: aarch64 CI

on: [push]

jobs:
  actions_job:
    runs-on: ubuntu-latest
    name: A job to test the multi architecture action
    steps:
    - uses: actions/checkout@v1
    - name: Run some commands on arm64
      id: runcmd
      uses: WongTusnYan/bolt@master
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: | 
         uname -a
         whoami
         cat /etc/issue
         lscpu
         df -h
         pwd
         ls /github/workspace
         wget https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1.tar.gz
         tar -zxvf cmake-3.15.1.tar.gz
         cd cmake-3.15.1
         ./bootstrap
         make &&  make install
         cmake --version
         

